### ISSUE TITLE
Chat Extends Crashing for some users

### ISSUE THREAD

**Issue by Questionguy663** [torahamu/TOSAddon#10]
Since the most recent version of IToS (Visual Studio 2015 Update) 

When loading the game the function to  auto-create-directory crashes a lot of people. The game loads fine with other addons, or with no addons. But once this one is used a crash to desktop always happens when it makes the windows CMD prompt looking box.

https://youtu.be/cqhBq9JNX_A

The text says "The syntax of the command is incorrect"

My resolution is 3440x1440,  21:9 aspect ratio (quite unusual) if that is the problem.

**Comment by torahamu** [comment]
Sorry for the late reply.
Thank you, I did not know that it will not work.
I'll look it up.

**Comment by Questionguy663** [comment]
Thank you! This addon is very important to us! 

![emoticon_0013](https://cloud.githubusercontent.com/assets/19497435/24920854/b2105cda-1ee0-11e7-8bb4-45565e43bd7c.PNG)

**Comment by torahamu** [comment]
I fixed it, chatextends 1.0.4.

Stopped the auto-create-directory.
The chat log is saved in the savechat directory, but if there is no savechat directory, save the chat log in the screenshot directory. (Because the savechat directory is not created automatically, you need to create it manually)

If you confirmed that addo-on, this issue will close.
![emoticon_0037](https://cloud.githubusercontent.com/assets/23138318/24960593/321862a6-1fd1-11e7-824f-e694e0ec9893.png)

**Comment by Questionguy663** [comment]
Thank you! works perfectly! Issue Solved!

![emoticon_0002](https://cloud.githubusercontent.com/assets/19497435/24961749/b899795e-1f91-11e7-8f00-0e248d8bfe3f.png)
